// lib/matchReport/labels.ts
// Same 55 "Team Stats" row labels the Python extractor (extract-PDF/extract_match_report.py)
// matches against, kept in sync so both tools produce identical `stats` JSON keys.
export const TEAM_STATS_LABELS = [
  "Goals",
  "xG",
  "Shots / on target",
  "Shots on post / blocked / wide",
  "From penalty area / on target",
  "Outside penalty area / on target",
  "Average shot distance (m)",
  "Corners",
  "Free kicks",
  "Offsides",
  "Fouls / suffered",
  "Yellow / red cards",
  "Total / with shots",
  "Positional attacks / with shots",
  "Counterattacks",
  "Free kicks / with shots",
  "Corners / with shots",
  "Sliding tackles",
  "Interceptions",
  "Clearances",
  "Passes allowed per def. action (PPDA)",
  "Recoveries / low / medium / high",
  "Opponent half recoveries",
  "Losses / low / medium / high",
  "Total duels / won",
  "Offensive duels / won",
  "Defensive duels / won",
  "Loose ball duels / won",
  "Aerial duels / won",
  "Challenge intensity",
  "Dribbles / successful",
  "Possession %",
  "Pure possession time",
  "Number of possessions",
  "Possessions reaching opponent half",
  "Possessions reaching opponent penalty area",
  "Average possession duration",
  "Dead time",
  "Total passes / accurate",
  "Forward passes / accurate",
  "Back passes / accurate",
  "Lateral passes / accurate",
  "Progressive passes / accurate",
  "Long passes / accurate",
  "Passes to final third / accurate",
  "Average pass to final third length (m)",
  "Passes to penalty area / accurate",
  "Smart passes / accurate",
  "Shot assists",
  "Through passes / accurate",
  "Crosses / accurate",
  "Crosses: low / high / blocked",
  "Deep completions",
  "Match tempo",
  "Average pass length (m)",
].sort((a, b) => b.length - a.length); // longest first, so a short label never shadows a longer one it's a prefix of

export { slug } from "../slug";
