export type Metric = { key: string; label: string; weight: number };

export const KEY_METRICS: Record<string, Metric[]> = {
  GK: [
    { key: 'prevented_goals_per90', label: 'Prevented Goals/90', weight: 22.5 },
    { key: 'shot_stopping_quality', label: 'Shot Stopping Quality', weight: 12.5 },
    { key: 'aerial_ability_gk', label: 'Aerial Ability', weight: 12.5 },
    { key: 'exits_per90', label: 'Exits/90', weight: 12.5 },
    { key: 'passes_quality', label: 'Passes Quality', weight: 10 },
    { key: 'long_passes_quality', label: 'Long Passes Quality', weight: 7.5 },
    { key: 'back_passes_received_as_gk_per90', label: 'Back Passes as GK', weight: 7.5 },
  ],
  'RB/LB': [
    { key: 'progressive_passes_quality', label: 'Progressive Passes Quality', weight: 15 },
    { key: 'crosses_quality', label: 'Crosses Quality', weight: 12.5 },
    { key: 'defensive_duels_quality', label: 'Defensive Duels Quality', weight: 15 },
    { key: 'carrying_quality', label: 'Carrying Quality', weight: 10 },
    { key: 'passes_to_final_third_quality', label: 'Passes to Final Third', weight: 10 },
    { key: 'xa_per90', label: 'xA/90', weight: 10 },
    { key: 'dribbles_quality', label: 'Dribbles Quality', weight: 10 },
  ],
  CB: [
    { key: 'defensive_duels_quality', label: 'Defensive Duels Quality', weight: 20 },
    { key: 'aerial_quality', label: 'Aerial Quality', weight: 15 },
    { key: 'progressive_passes_quality', label: 'Progressive Passes Quality', weight: 15 },
    { key: 'padj_interceptions', label: 'PAdj Interceptions', weight: 10 },
    { key: 'passes_quality', label: 'Passes Quality', weight: 10 },
    { key: 'defensive_activity', label: 'Defensive Activity', weight: 10 },
    { key: 'long_passes_quality', label: 'Long Passes Quality', weight: 10 },
  ],
  DM: [
    { key: 'padj_interceptions', label: 'PAdj Interceptions', weight: 15 },
    { key: 'defensive_duels_quality', label: 'Defensive Duels Quality', weight: 15 },
    { key: 'aerial_quality', label: 'Aerial Quality', weight: 10 },
    { key: 'passes_quality', label: 'Passes Quality', weight: 10 },
    { key: 'forward_passes_quality', label: 'Forward Passes Quality', weight: 10 },
    { key: 'received_passes_per90', label: 'Received Passes', weight: 10 },
    { key: 'progressive_passes_per90', label: 'Progressive Passes', weight: 10 },
  ],
  CM: [
    { key: 'creativity_quality', label: 'Creativity Quality', weight: 20 },
    { key: 'progressive_passes_quality', label: 'Progressive Passes Quality', weight: 15 },
    { key: 'passes_quality', label: 'Passes Quality', weight: 10 },
    { key: 'forward_passes_quality', label: 'Forward Passes Quality', weight: 10 },
    { key: 'carrying_quality', label: 'Carrying Quality', weight: 10 },
    { key: 'padj_interceptions', label: 'PAdj Interceptions', weight: 10 },
    { key: 'received_passes_per90', label: 'Received Passes', weight: 10 },
  ],
  AM: [
    { key: 'xa_per90', label: 'xA/90', weight: 18 },
    { key: 'shot_assists_per90', label: 'Shot Assists/90', weight: 12 },
    { key: 'finishing_efficiency', label: 'Finishing Efficiency', weight: 12.5 },
    { key: 'xg_per90', label: 'xG/90', weight: 12.5 },
    { key: 'dribbles_quality', label: 'Dribbles Quality', weight: 12 },
    { key: 'progressive_passes_quality', label: 'Progressive Passes Quality', weight: 12 },
    { key: 'smart_passes_quality', label: 'Smart Passes Quality', weight: 10 },
  ],
  'RW/LW': [
    { key: 'finishing_efficiency', label: 'Finishing Efficiency', weight: 17.5 },
    { key: 'xg_per90', label: 'xG/90', weight: 20 },
    { key: 'dribbles_quality', label: 'Dribbles Quality', weight: 15 },
    { key: 'offensive_duels_quality', label: 'Offensive Duels Quality', weight: 10 },
    { key: 'xa_per90', label: 'xA/90', weight: 10 },
    { key: 'crosses_quality', label: 'Crosses Quality', weight: 7.5 },
    { key: 'carrying_quality', label: 'Carrying Quality', weight: 5 },
  ],
  CF: [
    { key: 'goals_per90', label: 'Goals/90', weight: 25 },
    { key: 'xg_per90', label: 'xG/90', weight: 15 },
    { key: 'shots_quality', label: 'Shots Quality', weight: 12.5 },
    { key: 'touches_in_box_per90', label: 'Touches in Box/90', weight: 12.5 },
    { key: 'finishing_efficiency', label: 'Finishing Efficiency', weight: 10 },
    { key: 'offensive_duels_quality', label: 'Offensive Duels Quality', weight: 10 },
    { key: 'aerial_quality', label: 'Aerial Quality', weight: 5 },
  ],
};

export const POSITION_DB_VALUES: Record<string, string[]> = {
  GK: ['GK'],
  'RB/LB': ['RB', 'LB'],
  CB: ['CB'],
  DM: ['DM'],
  CM: ['CM'],
  AM: ['AM'],
  'RW/LW': ['RW', 'LW'],
  CF: ['CF'],
};
