-- Season reset: relegated teams out, new-season base stats for continuing
-- teams (including Malut United FC, renamed to Java United this season),
-- brand-new promoted teams inserted with a zeroed stat line.
-- Run this once in the Supabase SQL editor (Project -> SQL Editor).

-- 1. Remove relegated teams
DELETE FROM liga_1_2026_2027 WHERE "Team" IN ('Persis Solo', 'PSBS Biak', 'Semen Padang FC');

-- 2. Rename Malut United FC -> Java United (same club, new name)
UPDATE liga_1_2026_2027 SET "Team" = 'Java United' WHERE "Team" = 'Malut United FC';

-- 3. Reset core columns for continuing teams (incl. Java United) to this season's numbers
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 2, "D" = 0, "L" = 0, goals = 6, opp_goals = 2 WHERE "Team" = 'Bali United FC';
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 2, "D" = 0, "L" = 0, goals = 5, opp_goals = 1 WHERE "Team" = 'Madura United FC';
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 2, "D" = 0, "L" = 0, goals = 3, opp_goals = 1 WHERE "Team" = 'Persija Jakarta';
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 1, "D" = 1, "L" = 0, goals = 7, opp_goals = 3 WHERE "Team" = 'Arema FC';
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 1, "D" = 1, "L" = 0, goals = 4, opp_goals = 3 WHERE "Team" = 'Persita Tangerang';
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 1, "D" = 1, "L" = 0, goals = 3, opp_goals = 2 WHERE "Team" = 'Dewa United FC';
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 1, "D" = 1, "L" = 0, goals = 2, opp_goals = 1 WHERE "Team" = 'Persebaya Surabaya';
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 1, "D" = 0, "L" = 1, goals = 4, opp_goals = 3 WHERE "Team" = 'Persib Bandung';
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 1, "D" = 0, "L" = 1, goals = 2, opp_goals = 1 WHERE "Team" = 'Persik Kediri';
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 1, "D" = 0, "L" = 1, goals = 1, opp_goals = 1 WHERE "Team" = 'Borneo FC Samarinda';
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 0, "D" = 2, "L" = 0, goals = 3, opp_goals = 3 WHERE "Team" = 'Bhayangkara Presisi FC';
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 0, "D" = 1, "L" = 1, goals = 1, opp_goals = 2 WHERE "Team" = 'PSIM Yogyakarta';
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 0, "D" = 1, "L" = 1, goals = 4, opp_goals = 6 WHERE "Team" = 'PSM Makassar';
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 0, "D" = 0, "L" = 2, goals = 0, opp_goals = 3 WHERE "Team" = 'Persijap Jepara';
UPDATE liga_1_2026_2027 SET "MP" = 2, "W" = 0, "D" = 1, "L" = 1, goals = 3, opp_goals = 4 WHERE "Team" = 'Java United';

-- 4. Insert newly promoted teams (every other numeric column zeroed)
INSERT INTO liga_1_2026_2027 ("Team", "Style", "Defense", "Physical", "MP", "W", "D", "L", "Poss %", "Poss % (Neutral)", "Direct %", "Territory %", "Pass Acc %", "xG/Shot", "KP/Shot", "Proactive Def %", "Step-Out %", "Aerial %", "logo_url", "club_id", "passes", "acc_passes", "long_balls", "acc_long_balls", "assists", "own_half_passes", "acc_own_half_passes", "opp_half_passes", "acc_opp_half_passes", "crosses", "acc_crosses", "key_passes", "aerial_duels_lost", "aerial_duels_won", "duels_lost", "duels_won", "challenges_lost", "contests", "contests_won", "shots", "shots_on_target", "shots_off_target", "shots_blocked", "goals", "hit_woodwork", "big_chances_missed", "xg", "clearances", "blocked_shots", "interceptions", "ball_recoveries", "tackles", "tackles_won", "errors_to_shot", "dispossessed", "fouls_drawn", "fouls_committed", "offsides", "pen_conceded", "pen_won", "own_goals", "crosses_not_claimed", "high_claims", "saves_box", "saves", "sweeper_actions", "acc_sweeper_actions", "touches", "unsuccessful_touches", "possession_lost", "opp_passes", "opp_acc_passes", "opp_long_balls", "opp_acc_long_balls", "opp_assists", "opp_own_half_passes", "opp_acc_own_half_passes", "opp_opp_half_passes", "opp_acc_opp_half_passes", "opp_crosses", "opp_acc_crosses", "opp_key_passes", "opp_aerial_duels_lost", "opp_aerial_duels_won", "opp_duels_lost", "opp_duels_won", "opp_challenges_lost", "opp_contests", "opp_contests_won", "opp_shots", "opp_shots_on_target", "opp_shots_off_target", "opp_shots_blocked", "opp_goals", "opp_hit_woodwork", "opp_big_chances_missed", "opp_xg", "opp_clearances", "opp_blocked_shots", "opp_interceptions", "opp_ball_recoveries", "opp_tackles", "opp_tackles_won", "opp_errors_to_shot", "opp_dispossessed", "opp_fouls_drawn", "opp_fouls_committed", "opp_offsides", "opp_pen_conceded", "opp_pen_won", "opp_own_goals", "opp_crosses_not_claimed", "opp_high_claims", "opp_saves_box", "opp_saves", "opp_sweeper_actions", "opp_acc_sweeper_actions", "opp_touches", "opp_unsuccessful_touches", "opp_possession_lost") VALUES ('Garudayaksa', 'Balanced', 'Balanced', 'Balanced', 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO liga_1_2026_2027 ("Team", "Style", "Defense", "Physical", "MP", "W", "D", "L", "Poss %", "Poss % (Neutral)", "Direct %", "Territory %", "Pass Acc %", "xG/Shot", "KP/Shot", "Proactive Def %", "Step-Out %", "Aerial %", "logo_url", "club_id", "passes", "acc_passes", "long_balls", "acc_long_balls", "assists", "own_half_passes", "acc_own_half_passes", "opp_half_passes", "acc_opp_half_passes", "crosses", "acc_crosses", "key_passes", "aerial_duels_lost", "aerial_duels_won", "duels_lost", "duels_won", "challenges_lost", "contests", "contests_won", "shots", "shots_on_target", "shots_off_target", "shots_blocked", "goals", "hit_woodwork", "big_chances_missed", "xg", "clearances", "blocked_shots", "interceptions", "ball_recoveries", "tackles", "tackles_won", "errors_to_shot", "dispossessed", "fouls_drawn", "fouls_committed", "offsides", "pen_conceded", "pen_won", "own_goals", "crosses_not_claimed", "high_claims", "saves_box", "saves", "sweeper_actions", "acc_sweeper_actions", "touches", "unsuccessful_touches", "possession_lost", "opp_passes", "opp_acc_passes", "opp_long_balls", "opp_acc_long_balls", "opp_assists", "opp_own_half_passes", "opp_acc_own_half_passes", "opp_opp_half_passes", "opp_acc_opp_half_passes", "opp_crosses", "opp_acc_crosses", "opp_key_passes", "opp_aerial_duels_lost", "opp_aerial_duels_won", "opp_duels_lost", "opp_duels_won", "opp_challenges_lost", "opp_contests", "opp_contests_won", "opp_shots", "opp_shots_on_target", "opp_shots_off_target", "opp_shots_blocked", "opp_goals", "opp_hit_woodwork", "opp_big_chances_missed", "opp_xg", "opp_clearances", "opp_blocked_shots", "opp_interceptions", "opp_ball_recoveries", "opp_tackles", "opp_tackles_won", "opp_errors_to_shot", "opp_dispossessed", "opp_fouls_drawn", "opp_fouls_committed", "opp_offsides", "opp_pen_conceded", "opp_pen_won", "opp_own_goals", "opp_crosses_not_claimed", "opp_high_claims", "opp_saves_box", "opp_saves", "opp_sweeper_actions", "opp_acc_sweeper_actions", "opp_touches", "opp_unsuccessful_touches", "opp_possession_lost") VALUES ('PSS', 'Balanced', 'Balanced', 'Balanced', 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO liga_1_2026_2027 ("Team", "Style", "Defense", "Physical", "MP", "W", "D", "L", "Poss %", "Poss % (Neutral)", "Direct %", "Territory %", "Pass Acc %", "xG/Shot", "KP/Shot", "Proactive Def %", "Step-Out %", "Aerial %", "logo_url", "club_id", "passes", "acc_passes", "long_balls", "acc_long_balls", "assists", "own_half_passes", "acc_own_half_passes", "opp_half_passes", "acc_opp_half_passes", "crosses", "acc_crosses", "key_passes", "aerial_duels_lost", "aerial_duels_won", "duels_lost", "duels_won", "challenges_lost", "contests", "contests_won", "shots", "shots_on_target", "shots_off_target", "shots_blocked", "goals", "hit_woodwork", "big_chances_missed", "xg", "clearances", "blocked_shots", "interceptions", "ball_recoveries", "tackles", "tackles_won", "errors_to_shot", "dispossessed", "fouls_drawn", "fouls_committed", "offsides", "pen_conceded", "pen_won", "own_goals", "crosses_not_claimed", "high_claims", "saves_box", "saves", "sweeper_actions", "acc_sweeper_actions", "touches", "unsuccessful_touches", "possession_lost", "opp_passes", "opp_acc_passes", "opp_long_balls", "opp_acc_long_balls", "opp_assists", "opp_own_half_passes", "opp_acc_own_half_passes", "opp_opp_half_passes", "opp_acc_opp_half_passes", "opp_crosses", "opp_acc_crosses", "opp_key_passes", "opp_aerial_duels_lost", "opp_aerial_duels_won", "opp_duels_lost", "opp_duels_won", "opp_challenges_lost", "opp_contests", "opp_contests_won", "opp_shots", "opp_shots_on_target", "opp_shots_off_target", "opp_shots_blocked", "opp_goals", "opp_hit_woodwork", "opp_big_chances_missed", "opp_xg", "opp_clearances", "opp_blocked_shots", "opp_interceptions", "opp_ball_recoveries", "opp_tackles", "opp_tackles_won", "opp_errors_to_shot", "opp_dispossessed", "opp_fouls_drawn", "opp_fouls_committed", "opp_offsides", "opp_pen_conceded", "opp_pen_won", "opp_own_goals", "opp_crosses_not_claimed", "opp_high_claims", "opp_saves_box", "opp_saves", "opp_sweeper_actions", "opp_acc_sweeper_actions", "opp_touches", "opp_unsuccessful_touches", "opp_possession_lost") VALUES ('Isenmulang', 'Balanced', 'Balanced', 'Balanced', 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
