-- Match events timeline (goals, cards, substitutions), parsed from the match
-- report PDF: goals from page 1's cover (cross-checked against icon color to
-- exclude red-card entries, which use the same "71' Player Name" format),
-- cards + substitutions from page 2's lineup ("Starting lineup" / "Substitutes"
-- sections) by classifying each minute marker's icon color (yellow card
-- #f7ca18, red card #c81729, sub-out arrow #d42e36, sub-in arrow #2ab144).
-- Substitution pairs (who replaced whom) are matched by same team + same
-- lineup position code + same minute.
-- Supersedes the never-migrated match_goals table (goals now live here as
-- event_type='goal' instead).
create table if not exists match_events (
  id bigint generated by default as identity primary key,
  match_id bigint not null references matches(id) on delete cascade,
  club_id bigint not null references clubs(id) on delete cascade,
  event_type text not null check (event_type in ('goal', 'yellow_card', 'red_card', 'substitution')),
  -- Text, not int, to preserve stoppage-time minutes like "45+2".
  minute text not null,
  -- Scorer / carded player / player going off (substitution).
  player_id bigint references players(id) on delete set null,
  player_name_raw text not null,
  -- Substitution only: the player coming on.
  sub_in_player_id bigint references players(id) on delete set null,
  sub_in_player_name_raw text,
  created_at timestamptz not null default now()
);

alter table match_events enable row level security;

drop policy if exists "match_events_authenticated_all" on match_events;
create policy "match_events_authenticated_all" on match_events for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
