-- Starting XI per match (jersey, formation slot, player), parsed from the
-- match report PDF's "Starting lineup" section on the lineup page. Powers
-- the pitch/formation view in the match report's "Lineup" tab — position_code
-- (e.g. "LCB", "RDMF", "CF") is mapped to an on-pitch (x%, y%) client-side,
-- grouped by depth band and left/center/right lane, so it adapts to any
-- formation shape rather than needing a hardcoded layout per formation.
create table if not exists match_lineups (
  id bigint generated by default as identity primary key,
  match_id bigint not null references matches(id) on delete cascade,
  club_id bigint not null references clubs(id) on delete cascade,
  player_id bigint references players(id) on delete set null,
  player_name_raw text not null,
  jersey_number int,
  position_code text not null,
  created_at timestamptz not null default now()
);

alter table match_lineups enable row level security;

drop policy if exists "match_lineups_authenticated_all" on match_lineups;
create policy "match_lineups_authenticated_all" on match_lineups for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
