-- Videos table for the PSIM Yogyakarta Supabase project — match footage,
-- training clips, and opponent scouting videos, embedded from a pasted
-- YouTube or Google Drive share link (no file storage/upload involved).
create table if not exists videos (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  category text not null default 'Match',
  description text,
  created_at timestamptz not null default now()
);

alter table videos enable row level security;

create policy "videos_authenticated_all" on videos for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
