-- Standings table for the PSIM Yogyakarta Supabase project — current-season
-- (2026/2027) league table, entered manually since `matches` only tracks
-- PSIM's own fixtures (not the other 17 clubs' matches against each other)
-- and the old project's liga_1_2026_2027 table turned out to be last
-- season's completed standings, not this season's in-progress ones.
create table if not exists standings (
  id bigint generated by default as identity primary key,
  club_id bigint not null references clubs(id) on delete cascade,
  mp int not null default 0,
  w int not null default 0,
  d int not null default 0,
  l int not null default 0,
  goals_for int not null default 0,
  goals_against int not null default 0,
  -- Stored directly (not derived from w*3+d) since the league can apply
  -- point deductions — some clubs' real points don't match their W/D/L.
  points int not null default 0,
  updated_at timestamptz not null default now(),
  unique (club_id)
);

alter table standings enable row level security;

create policy "standings_authenticated_all" on standings for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
